# see http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.10.4
script: ./buildall.sh
notifications:
  email:
    recipients:
      - lossyrob@gmail.com
      - echeipesh@gmail.com
  irc:
      - "irc.freenode.org#geotrellis"
  use_notice: true

jdk:
  - openjdk7
  - oraclejdk7