# see http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.9.2
script: wget https://raw.github.com/paulp/sbt-extras/master/sbt && chmod u+x ./sbt && ./sbt -mem 512 test
notifications:
  email:
    recipients:
      - jmarcus@azavea.com
  irc:
      - "irc.freenode.org#geotrellis"
  use_notice: true
