# see http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.9.2
script: ./buildall.sh
notifications:
  email:
    recipients:
      - lossyrob@gmail.com
  irc:
      - "irc.freenode.org#geotrellis"
  use_notice: true
