site_name: GeoTrellis
site_description: A Scala library for high-performance geographic data processing.
site_author: GeoTrellis Team
repo_url: https://github.com/geotrellis/geotrellis
copyright: Copyright (c) 2012-2016, Azavea
docs_dir: docs
theme: readthedocs

pages:
  - Home: index.md
  - Changelog: CHANGELOG.md
  - Tutorials:
      - Setup: tutorials/setup.md
  - User Guide:
    - GeoTrellis Module Hierarchy: guide/module-hierarchy.md
  - Architecture:
      - Architecture Decision Records: architecture/adr.md

markdown_extensions:
- toc:
    permalink: true
