---

#Main tasks for hadoop master
- apt: name=hadoop-hdfs state=present force=yes
  sudo: yes

- include_vars: group_vars/cluster.yml  

- name: Upload Hadoop config
  template: src=conf/{{ item }} dest=/etc/hadoop/conf
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - hadoop-env.sh
    - log4j.properties
  sudo: yes
  notify: 
    - Restart Hadoop Datanode
    - Restart Hadoop Namenode

- lineinfile: 
    dest="/etc/environment"
    regexp="^HADOOP_PREFIX=" 
    line="HADOOP_PREFIX=/usr/lib/hadoop"
  sudo: yes

- lineinfile: 
    dest="/etc/environment"
    regexp="^HADOOP_CONF_DIR=" 
    line="HADOOP_CONF_DIR=/etc/hadoop/conf"
  sudo: yes

- include: "namenode.yml"
  when: '"master" in group_names'

- include: "datanode.yml"
  when: '"workers" in group_names'